#!/usr/bin/env node
"use strict";
const fs=require("fs"),path=require("path"),http=require("http"),crypto=require("crypto");
function findPlaywright(){const root="/root/.npm/_npx";const choices=fs.readdirSync(root).map(name=>path.join(root,name,"node_modules","playwright")).filter(item=>fs.existsSync(path.join(item,"package.json")));if(!choices.length)throw new Error("Playwright package not found; run Playwright CLI first");choices.sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs);return require(choices[0])}
const {chromium}=findPlaywright();const reviewRoot=path.resolve(__dirname,".."),modelRoot=path.resolve(reviewRoot,"../.."),modelKey=path.basename(modelRoot),workspace=path.resolve(modelRoot,"..");
const configs={"Dell-R240-3.5inch":{standard:"model/Dell-R240-3.5inch.glb",web:"model/Dell-R240-3.5inch-web.glb"},"Dell-R630-2.5inch":{standard:"model/Dell-R630-2.5inch.glb",web:"model/Dell-R630-2.5inch-web.glb"},"Dell-C6320-2.5inch":{standard:"models/Dell-PowerEdge-C6300-4xC6320-24SFF-standard.glb",web:"models/Dell-PowerEdge-C6300-4xC6320-24SFF-web.glb"}};if(!configs[modelKey])throw new Error(`unsupported in-scope model ${modelKey}`);
const frozen=JSON.parse(fs.readFileSync(path.join(reviewRoot,"final","frozen-hashes.json"),"utf8"));const expected={standard:frozen.standardGlb.sha256,web:frozen.webGlb.sha256};
const mime={".html":"text/html",".js":"text/javascript",".mjs":"text/javascript",".glb":"model/gltf-binary",".png":"image/png"};function resolveSafe(url){const file=path.resolve(workspace,"."+decodeURIComponent(url.split("?")[0]));if(!file.startsWith(workspace+path.sep))throw new Error("out-of-scope path");return file}function digest(file){return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex")}
const views=[["front",0,0],["rear",180,0],["left",270,0],["right",90,0],["top",0,89],["bottom",0,-89],["front-left",315,25],["front-right",45,25],["rear-left",225,25],["rear-right",135,25]];
async function main(){for(const variant of ["standard","web"]){const actual=digest(path.join(modelRoot,configs[modelKey][variant]));if(actual!==expected[variant])throw new Error(`${variant} changed after freeze: ${actual}`)}
  const server=http.createServer((req,res)=>{try{const file=resolveSafe(req.url),stat=fs.statSync(file);if(!stat.isFile())throw new Error("not file");res.writeHead(200,{"Content-Type":mime[path.extname(file)]||"application/octet-stream","Cache-Control":"no-store, max-age=0","Access-Control-Allow-Origin":"*"});fs.createReadStream(file).pipe(res)}catch(error){res.writeHead(404);res.end(String(error))}});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const port=server.address().port,browser=await chromium.launch({headless:true,args:["--use-angle=swiftshader","--enable-webgl","--ignore-gpu-blocklist"]});const outRoot=path.join(reviewRoot,"final","static-40-loads");fs.mkdirSync(outRoot,{recursive:true});const records=[];let ordinal=0;
  try{for(const engine of ["three","babylon"])for(const variant of ["standard","web"]){const combo=[];const modelFile=path.join(modelRoot,configs[modelKey][variant]),relative="/"+path.relative(workspace,modelFile).split(path.sep).join("/");const comboDir=path.join(outRoot,engine,variant);fs.mkdirSync(comboDir,{recursive:true});for(const [name,yaw,pitch] of views){ordinal++;const nonce=`${Date.now()}-${ordinal}-${engine}-${variant}-${name}`,page=await browser.newPage({viewport:{width:640,height:480},deviceScaleFactor:1}),consoleErrors=[];page.on("console",msg=>{if(msg.type()==="error")consoleErrors.push(msg.text())});page.on("pageerror",error=>consoleErrors.push(String(error)));const viewer=`http://127.0.0.1:${port}/${modelKey}/qa/rotation-review-20260827/viewers/${engine}-orbit.html`,modelUrl=`http://127.0.0.1:${port}${relative}?cb=${nonce}`,pageUrl=`${viewer}?model=${encodeURIComponent(modelUrl)}&yaw=${yaw}&pitch=${pitch}&bg=${ordinal%2?"light":"dark"}&load=${nonce}`;const started=Date.now();await page.goto(pageUrl,{waitUntil:"domcontentloaded",timeout:120000});await page.waitForFunction(()=>window.qaReady===true||window.qaError,{timeout:120000});const failure=await page.evaluate(()=>window.qaError||null);if(failure)throw new Error(failure);const runtime=await page.evaluate(()=>({...window.qaInfo,overlayVisible:getComputedStyle(document.getElementById("loading")).display!=="none"}));if(!runtime.webgl2||runtime.overlayVisible||runtime.modelSha256!==expected[variant])throw new Error(`load gate failed ${engine}/${variant}/${name}`);const filename=`${String(views.findIndex(item=>item[0]===name)+1).padStart(2,"0")}-${name}.png`;const shot=await page.screenshot({path:path.join(comboDir,filename),type:"png"});const record={ordinal,engine,variant,view:name,yaw,pitch,nonce,cacheBusted:true,independentNewPage:true,modelSha256:runtime.modelSha256,viewerEngine:runtime.engine,webgl2:runtime.webgl2,overlayVisible:runtime.overlayVisible,consoleErrors,elapsedMs:Date.now()-started,screenshot:path.relative(reviewRoot,path.join(comboDir,filename)),screenshotSha256:crypto.createHash("sha256").update(shot).digest("hex")};records.push(record);combo.push(record);await page.close()}fs.writeFileSync(path.join(comboDir,"load-manifest.json"),JSON.stringify({modelKey,engine,variant,loadCount:combo.length,loads:combo},null,2)+"\n");process.stderr.write(`${modelKey} ${engine}/${variant}: 10 cache-busted independent loads\n`)}
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
  const report={modelKey,capturedAt:new Date().toISOString(),frozenAt:frozen.frozenAt,loadCount:records.length,engines:["three","babylon"],variants:["standard","web"],views:views.map(item=>item[0]),allWebgl2:records.every(item=>item.webgl2),allHashesMatch:records.every(item=>item.modelSha256===expected[item.variant]),overlayFrameCount:records.filter(item=>item.overlayVisible).length,consoleErrorCount:records.reduce((sum,item)=>sum+item.consoleErrors.length,0),loads:records};fs.writeFileSync(path.join(outRoot,"load-run.json"),JSON.stringify(report,null,2)+"\n");process.stdout.write(JSON.stringify({modelKey,loadCount:report.loadCount,allWebgl2:report.allWebgl2,allHashesMatch:report.allHashesMatch,overlayFrameCount:report.overlayFrameCount,consoleErrorCount:report.consoleErrorCount},null,2)+"\n")}
main().catch(error=>{console.error(error);process.exitCode=1});
