(function(){
  const params=new URLSearchParams(location.search),modelURL=params.get('model')||'../../model/HPE-DL360G10-2.5inch.glb',viewName=params.get('view')||'front-right',bgName=params.get('bg')||'light';
  const status=document.querySelector('#status'),renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1200,800,false);renderer.setPixelRatio(1);renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.NoToneMapping;renderer.setClearColor(bgName==='dark'?0x091018:0xe8ecef,1);document.body.prepend(renderer.domElement);
  const scene=new THREE.Scene();
  if(bgName==='checker-light' || bgName==='checker-dark'){
    const dark=bgName==='checker-dark',canvas=document.createElement('canvas');canvas.width=1200;canvas.height=800;
    const context=canvas.getContext('2d'),cell=40,colors=dark?['#091018','#283038']:['#edf0f2','#afb7bf'];
    for(let y=0;y<canvas.height;y+=cell)for(let x=0;x<canvas.width;x+=cell){context.fillStyle=colors[((x/cell)+(y/cell))&1];context.fillRect(x,y,cell,cell)}
    const texture=new THREE.CanvasTexture(canvas);texture.encoding=THREE.sRGBEncoding;scene.background=texture;
  }
  const defs={front:[[0,0,1],[0,1,0],1],rear:[[0,0,-1],[0,1,0],1],left:[[-1,0,0],[0,1,0],1],right:[[1,0,0],[0,1,0],1],top:[[0,1,0],[0,0,-1],1],bottom:[[0,-1,0],[0,0,1],1],'front-left':[[-.72,.34,.92],[0,1,0],0],'front-right':[[.72,.34,.92],[0,1,0],0],'rear-left':[[-.72,.34,-.92],[0,1,0],0],'rear-right':[[.72,.34,-.92],[0,1,0],0]};
  function corners(box){const a=[];for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z])a.push(new THREE.Vector3(x,y,z));return a}
  function cameraFor(root){const [d0,u0,isOrtho]=defs[viewName]||defs['front-right'],d=new THREE.Vector3(...d0).normalize(),up=new THREE.Vector3(...u0),box=new THREE.Box3().setFromObject(root),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),radius=size.length()/2;
    if(isOrtho){const cam=new THREE.OrthographicCamera(-1,1,1,-1,.1,5000);cam.up.copy(up);cam.position.copy(center).addScaledVector(d,1200);cam.lookAt(center);cam.updateMatrixWorld(true);let mx=0,my=0;for(const p of corners(box)){p.applyMatrix4(cam.matrixWorldInverse);mx=Math.max(mx,Math.abs(p.x));my=Math.max(my,Math.abs(p.y))}mx*=1.10;my*=1.10;const aspect=1200/800;if(mx/my<aspect)mx=my*aspect;else my=mx/aspect;cam.left=-mx;cam.right=mx;cam.bottom=-my;cam.top=my;cam.updateProjectionMatrix();return cam}
    const cam=new THREE.PerspectiveCamera(34,1200/800,.1,5000),dist=radius/Math.tan(THREE.MathUtils.degToRad(17))*1.08;cam.up.copy(up);cam.position.copy(center).addScaledVector(d,dist);cam.lookAt(center);cam.updateProjectionMatrix();return cam}
  new THREE.GLTFLoader().load(modelURL,gltf=>{scene.add(gltf.scene);gltf.scene.updateMatrixWorld(true);const camera=cameraFor(gltf.scene);const nodes=[];gltf.scene.traverse(o=>nodes.push(o));const bottom=gltf.scene.getObjectByName('Bottom_TexturePlane_GENERIC_BOTTOM_FALLBACK');window.__GLTF_ROOT__=gltf.scene;window.__BOTTOM__=bottom;window.__CAMERA__=camera;window.__RENDERER__=renderer;window.__SCENE__=scene;const bottomState=bottom?`bottom-map:${bottom.material?.map?'yes':'no'} side:${bottom.material?.side}`:'bottom-missing';let frame=0;const finish=()=>{renderer.render(scene,camera);if(++frame<3){requestAnimationFrame(finish);return}status.textContent=`PASS · ${viewName} · ${nodes.length} objects · ${bottomState}`;document.querySelector('#tag').textContent=`Viewer B · Three.js r128 · ${modelURL.includes('-web')?'web':'standard'} GLB`;window.__RENDER_DONE__=true};requestAnimationFrame(finish)},undefined,e=>{console.error(e);status.textContent=`ERROR ${e.message}`;window.__RENDER_DONE__='error'});
})();
