import pathlib,json,csv,pymupdf as f
P=pathlib.Path('/root/Blender/DELL-C6420/v001'); rows=[]
for r in json.loads((P/'sources/official/downloads.json').read_text()):
 rows.append(dict(source_page=r['url'],asset_url=r['url'],local_path='sources/official/'+r['name'],source_type='Dell official PDF',view='multiple; see extracted pages',actual_model='C6400 enclosure / C6420 node',node_count='4 target; multiple configs in document',drive_config='24x2.5 target; other configs explicitly excluded',pdf_page='Technical guide66; C6400 service7,9; C6420 specs4',confirmed_details='Dimensions and part layout; verify page-specific applicability',confidence='high',status=str(r['status'])))
rows.append(dict(source_page='https://downloads.dell.com/manuals/all-products/esuprt_solutions_int/esuprt_solutions_int_solutions_resources/high-computing-solution-resources_white-papers48_en-us.pdf',asset_url='https://downloads.dell.com/manuals/all-products/esuprt_solutions_int/esuprt_solutions_int_solutions_resources/high-computing-solution-resources_white-papers48_en-us.pdf',local_path='sources/official/hpc-design-whitepaper.pdf',source_type='Dell official whitepaper',view='cooling context only',actual_model='C6420 air/liquid options',node_count='multiple',drive_config='not used for geometry',pdf_page='all; not dimension authority',confirmed_details='Liquid cooling exists as option; target uses air cooling based on locked photos',confidence='high context; not chosen configuration',status='200'))
views={'nsl-C6400.png':'front elevated; top; branding; black bay fillers','nsl-_6400_back.png':'rear elevated; 4 nodes; 2 central EPP2400W; dualSFP/node','nsl-_6400_2.png':'front-right oblique; right side; top','nsl-C6420.png':'single bare node rear; unpopulated OCP, secondary structure only','nsl-C6420_1.png':'single bare node rear oblique; side; air cooling', 'etb-dell_poweredge_c6420_rear_4xmods_3_4.jpg':'rear; same stock photograph family as NSL; NOT independent photographic corroboration'}
for r in json.loads((P/'sources/third_party/images.json').read_text()):
 rows.append(dict(source_page=r['page'],asset_url=r['url'],local_path=str(pathlib.Path(r.get('path','')).relative_to(P)) if r.get('path') else '',source_type='Third party original product photo',view=views.get(r['name'],'single-node internal/component study'),actual_model='C6420 nodes in C6400' if ('6400' in r['name'] or '4xmods' in r['name']) else 'C6420 single node; reference only',node_count='4' if ('6400' in r['name'] or '4xmods' in r['name']) else '1',drive_config='24x2.5 enclosure; front NSL photo shows fillers',pdf_page='',confirmed_details='Original resolution '+str(r.get('size'))+'; no horizontal flip',confidence='high visual structure; unknown NIC chip identity',status=str(r.get('status',r.get('error')))))
for fn in ['pages.json','pages2.json']:
 for r in json.loads((P/'sources/third_party'/fn).read_text()):
  rows.append(dict(source_page=r.get('url',''),asset_url='',local_path='sources/third_party/'+r['name']+'.html',source_type='webpage fetch / access record',view='',actual_model='listing metadata only',node_count='',drive_config='',pdf_page='',confirmed_details='Direct HTTP '+str(r.get('status'))+'; 403 file is error page, not evidence. web search may expose indexed text.',confidence='unavailable' if r.get('status')!=200 else 'page available',status=str(r.get('status',r.get('error')))))
with (P/'sources.csv').open('w',newline='') as out:
 w=csv.DictWriter(out,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
# Preserve original embedded official diagrams; use these for faithful brand reference later.
d=f.open(P/'sources/official/c6400-service-manual.pdf')
for xref,n in [(85,'official-front-original'),(100,'official-controls-original'),(143,'official-rear-original')]:
 im=d.extract_image(xref);(P/'sources/extracted'/(n+'.'+im['ext'])).write_bytes(im['image'])
print('Source index:',len(rows),'rows; official embedded originals extracted')
