import pathlib,json,hashlib,datetime
P=pathlib.Path('/root/Blender/DELL-C6420/v001');G=P/'references/imagegen'
selected=['01-front-v3','02-rear-v1','03-left-v1','04-right-v2','05-top-v2','06-bottom-inferred-v1','07-front-left-v1','08-front-right-v1','09-rear-left-v1','10-rear-right-v1','11-high-oblique-v2','12-low-rear-inferred-v3','13-structural-sketch-v4','14-assembly-sketch-v2','15-sections-sketch-v1','16-brand-detail-v1','17-carrier-detail-v1','18-control-area-detail-v1','19-rear-ports-detail-v1','20-node-latch-detail-v1','21-psu-detail-v1','22-vent-detail-v1']
def rel(s):return str(P/s)
standard=[rel('sources/third_party/nsl-_6400_2.png'),rel('sources/third_party/nsl-_6400_back.png'),rel('sources/extracted/official-front-24sff.png')]
overrides={'01-front-v1':[standard[0],standard[1],rel('sources/extracted/c6400-service-manual-p007.png')],'01-front-v2':[standard[0],standard[1],rel('sources/extracted/c6400-service-manual-p007.png')],'02-rear-v1':[standard[0],standard[1],rel('sources/extracted/c6400-service-manual-p007.png')],'01-front-v3':[standard[2]],'03-left-v1':[standard[0],standard[1],rel('sources/extracted/c6400-service-manual-p007.png')],'04-right-v1':[standard[0],standard[1],rel('sources/extracted/c6400-service-manual-p007.png')],'04-right-v2':[rel('references/imagegen/04-right-v1.png')],'05-top-v2':[standard[0]],'11-high-oblique-v2':[rel('references/imagegen/01-front-v3.png'),standard[0]],'12-low-oblique-inferred-v2':[rel('references/imagegen/01-front-v3.png'),rel('references/imagegen/06-bottom-inferred-v1.png')],'12-low-rear-inferred-v3':[standard[1],rel('references/imagegen/06-bottom-inferred-v1.png')],'13-structural-sketch-v2':[rel('references/imagegen/'+x+'.png') for x in ['01-front-v3','04-right-v2','05-top-v2']],'13-structural-sketch-v3':[standard[0]],'13-structural-sketch-v4':[rel('references/imagegen/13-structural-sketch-v3.png')],'14-assembly-sketch-v2':[standard[0],rel('sources/third_party/nsl-C6420_1.png')],'16-brand-detail-v1':[rel('sources/extracted/official-controls-original.jpeg')],'17-carrier-detail-v1':[standard[2]],'18-control-area-detail-v1':[rel('sources/extracted/official-controls-original.jpeg'),standard[0]],'19-rear-ports-detail-v1':[rel('sources/third_party/etb-dell_poweredge_c6420_rear_4xmods_3_4.jpg')],'20-node-latch-detail-v1':[rel('sources/third_party/nsl-C6420_1.png'),standard[1]],'21-psu-detail-v1':[rel('sources/third_party/etb-dell_poweredge_c6420_rear_4xmods_3_4.jpg')],'22-vent-detail-v1':[standard[1],standard[2]]}
raw={hashlib.sha256(f.read_bytes()).hexdigest():str(f) for f in pathlib.Path('/root/.codex/generated_images/01a07706-cbcd-7c73-a258-4751adc44258').glob('*.png')}
items=[]
for f in sorted(G.glob('*.png')):
 id=f.stem.replace('-rejected','');h=hashlib.sha256(f.read_bytes()).hexdigest()
 items.append({'id':id,'file':str(f.relative_to(P)),'selected':id in selected,'tool':'built-in image_gen.imagegen','sha256':h,'tool_original_file':raw.get(h),'prompt_file':'references/prompts/'+id+'.txt','input_references':overrides.get(id,standard),'view_and_purpose':id.split('-v')[0],'version':id.rsplit('-v',1)[-1],'evidence_status':'AI generated; never measured CAD; see qa-log.md for accepted region limitations','inferred':'bottom' in id or 'inferred' in id,'timestamp_utc':datetime.datetime.fromtimestamp(f.stat().st_mtime,datetime.timezone.utc).isoformat()})
(P/'references/manifest.json').write_text(json.dumps(items,ensure_ascii=False,indent=2));(P/'references/SELECTED.txt').write_text('\n'.join('imagegen/'+x+'.png' for x in selected)+'\n')
assert len(selected)==22 and all((G/(s+'.png')).exists() for s in selected)
print('22 selected assets;',len(items),'total generated versions')
