#!/usr/bin/env node
"use strict";
const fs=require("fs"),path=require("path"),http=require("http"),crypto=require("crypto");
function findPlaywright(){const root="/root/.npm/_npx";const choices=fs.readdirSync(root).map(name=>path.join(root,name,"node_modules","playwright")).filter(item=>fs.existsSync(path.join(item,"package.json")));choices.sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs);if(!choices.length)throw new Error("Playwright missing");return require(choices[0])}
const {chromium}=findPlaywright(),reviewRoot=path.resolve(__dirname,".."),modelRoot=path.resolve(reviewRoot,"../.."),modelKey=path.basename(modelRoot),workspace=path.resolve(modelRoot,"..");const configs={"Dell-R240-3.5inch":{standard:"model/Dell-R240-3.5inch.glb",web:"model/Dell-R240-3.5inch-web.glb"},"Dell-R630-2.5inch":{standard:"model/Dell-R630-2.5inch.glb",web:"model/Dell-R630-2.5inch-web.glb"},"Dell-C6320-2.5inch":{standard:"models/Dell-PowerEdge-C6300-4xC6320-24SFF-standard.glb",web:"models/Dell-PowerEdge-C6300-4xC6320-24SFF-web.glb"}};if(!configs[modelKey])throw new Error(modelKey);const frozen=JSON.parse(fs.readFileSync(path.join(reviewRoot,"final","frozen-hashes.json"))),expected={standard:frozen.standardGlb.sha256,web:frozen.webGlb.sha256};const views=[["front",0,0],["rear",180,0],["left",270,0],["right",90,0],["top",0,89],["bottom",0,-89]];const mime={".html":"text/html",".js":"text/javascript",".mjs":"text/javascript",".glb":"model/gltf-binary"};
function safe(url){const file=path.resolve(workspace,"."+decodeURIComponent(url.split("?")[0]));if(!file.startsWith(workspace+path.sep))throw new Error("scope");return file}function sha(file){return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex")}
async function main(){const server=http.createServer((req,res)=>{try{const file=safe(req.url);res.writeHead(200,{"Content-Type":mime[path.extname(file)]||"application/octet-stream","Cache-Control":"no-store","Access-Control-Allow-Origin":"*"});fs.createReadStream(file).pipe(res)}catch(error){res.writeHead(404);res.end(String(error))}});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const port=server.address().port,browser=await chromium.launch({headless:true,args:["--use-angle=swiftshader","--enable-webgl","--ignore-gpu-blocklist"]}),records=[];
  try{for(const engine of ["three","babylon"])for(const variant of ["standard","web"]){const file=path.join(modelRoot,configs[modelKey][variant]);if(sha(file)!==expected[variant])throw new Error("frozen GLB changed");const page=await browser.newPage({viewport:{width:640,height:480},deviceScaleFactor:1}),relative="/"+path.relative(workspace,file).split(path.sep).join("/"),nonce=`${Date.now()}-${engine}-${variant}`,viewer=`http://127.0.0.1:${port}/${modelKey}/qa/rotation-review-20260827/viewers/${engine}-orbit.html`,modelUrl=`http://127.0.0.1:${port}${relative}?cb=${nonce}`;await page.goto(`${viewer}?model=${encodeURIComponent(modelUrl)}&yaw=0&pitch=0&bg=light`,{waitUntil:"domcontentloaded",timeout:120000});await page.waitForFunction(()=>window.qaReady===true||window.qaError,{timeout:120000});const runtime=await page.evaluate(()=>window.qaInfo);if(!runtime.webgl2||runtime.modelSha256!==expected[variant])throw new Error("runtime gate");await page.evaluate(()=>{document.documentElement.style.background="transparent";document.body.style.background="transparent";document.body.style.backgroundImage="none"});const dir=path.join(reviewRoot,"final","matched-camera","renders",engine,variant);fs.mkdirSync(dir,{recursive:true});for(const [face,yaw,pitch] of views){await page.evaluate(value=>window.qaSetOrbit(value.yaw,value.pitch),{yaw,pitch});const output=path.join(dir,`${face}.png`),buffer=await page.screenshot({path:output,type:"png",omitBackground:true});records.push({engine,variant,face,yaw,pitch,modelSha256:runtime.modelSha256,file:path.relative(reviewRoot,output),screenshotSha256:crypto.createHash("sha256").update(buffer).digest("hex")})}await page.close();process.stderr.write(`${modelKey} ${engine}/${variant}: six transparent matched cameras\n`)}
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}const report={modelKey,capturedAt:new Date().toISOString(),frozenAt:frozen.frozenAt,captureCount:records.length,allHashesMatch:records.every(record=>record.modelSha256===expected[record.variant]),records};const out=path.join(reviewRoot,"final","matched-camera","capture-manifest.json");fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+"\n");process.stdout.write(JSON.stringify({modelKey,captureCount:records.length,allHashesMatch:report.allHashesMatch},null,2)+"\n")}
main().catch(error=>{console.error(error);process.exitCode=1});
