from pathlib import Path
from html import escape
import json
P=Path('/root/Project/rack-device-3d/Dell-C6420-2.5inch/v002')
views=[('front','正面 · 24正常盘架'),('rear','后面 · 4节点 / 双2400W电源'),('left','左面 · 部分孔位推估'),('right','右面'),('top','顶面 · 实拍标签'),('bottom','底面 · 通用推测'),('front-left','前左'),('front-right','前右'),('rear-left','后左'),('rear-right','后右'),('high-front','俯斜视'),('low-rear','仰斜视 · 底部推测'),('carrier-detail','正常热插拔盘架特写'),('brand-detail','真实品牌与控制面板'),('node-detail','节点接口特写'),('psu-detail','电源特写')]
parts=['''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>C6420 写实重做 v002 · 模型与检查</title><style>body{max-width:1280px;margin:32px auto;padding:0 24px;font:16px/1.6 system-ui,sans-serif;color:#202124;background:#f7f7f5}h1{font-size:30px;margin-bottom:8px}h2{font-size:23px;margin-top:40px}a{color:#065da3}p{max-width:1000px}nav{display:flex;flex-wrap:wrap;gap:20px;margin:22px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}figure{margin:0;background:white;border:1px solid #ddd;padding:12px}img{width:100%;height:330px;object-fit:contain;display:block}figcaption{padding:8px 0 0}.wide{height:auto;max-height:650px}button,input{font:inherit;padding:6px}input{width:60%}.note{color:#595959}table{border-collapse:collapse}td,th{padding:8px 14px;text-align:left;border-bottom:1px solid #ccc}@media(max-width:700px){.grid{grid-template-columns:1fr}img{height:260px}}</style><h1>Dell PowerEdge C6420 · 写实重做 v002</h1><p>四个C6420节点、C6400机箱、24个正常2.5英寸热插拔硬盘托架。前部采用三个拉手开窗、后置蜂窝网和橙圈释放按钮，保留真实DELL EMC与C6400品牌。v001已退回，本页仅展示v002最终成果。</p><nav><a href="model/DELL-PowerEdge-C6420-4N-24SFF.blend">可编辑Blender模型</a><a href="model/DELL-PowerEdge-C6420-4N-24SFF.glb">GLB模型</a><a href="QA.md">QA报告</a><a href="DIMENSIONS.md">官方尺寸</a><a href="sources.csv">来源索引</a><a href="REPRODUCE.md">编辑与复现</a></nav><p class="note">这是依据公开实拍与官方外廓尺寸重建的外观模型。底面、左侧局部孔位和隐蔽厚度存在明确推测；极小铭牌文字受原照片分辨率限制。没有将这些区域宣称为扫描级复刻。</p><h2>模型预览</h2><div class="grid">''']
for key,label in views:parts.append(f'<figure><a href="previews/{key}.png"><img loading="lazy" src="previews/{key}.png" alt="{label}"></a><figcaption>{label}</figcaption></figure>')
parts.append('</div><h2>与真实设备对照</h2><p>原始实拍没有水平翻转。不同配置只用于标明的局部：正常盘架依据Bargain整机前照；后部保持NSL/ETB同一套四节点2400W实体。NSL前图的塑料填充件已按用户要求替换。</p><div class="grid">')
pairs=[('sources/third_party/bargain-02.webp','真实整机：正常盘架；连续0–23编号与1600W选件未照搬'),('previews/source-front-comparison.png','v002：正常24盘架，官方四节点映射1-0…4-5'),('sources/third_party/etb-dell_poweredge_c6420_rear_4xmods_3_4.jpg','锁定的真实后部：四节点、中央双2400W电源'),('previews/source-rear-comparison.png','v002后部：相同端口数量和非对称方向'),('sources/third_party/nsl-_6400_2.png','真实前右：仅核对机身、顶盖、侧面及挂耳'),('previews/front-right.png','v002前右：正常托架取代原照填充件'),('sources/third_party/abacus-3.webp','补充真实顶盖标签：此照片不同NIC选件未采用'),('previews/top.png','v002顶面：真实印刷像素投影到已有凹面')]
for path,label in pairs:parts.append(f'<figure><a href="{path}"><img loading="lazy" src="{path}" alt="{escape(label)}"></a><figcaption>{escape(label)}</figcaption></figure>')
parts.append('''</div><h2>实际桌面旋转证据</h2><p>下方为最终GLB重新导入后、孔板法线修正后的360°检查：24次桌面旋转输入，保存9帧。原场景25帧另行保留。图像是软件OpenGL实际视口，角标表示累计输入；重绘可能短暂滞后，起终四元数另有闭合检查。</p><div><button id="play">播放 / 暂停</button> <input id="frame" type="range" min="0" max="8" value="0"><output id="angle">0°</output></div><a id="orbitlink" href="desktop/turntable-glb/frame-000.png"><img id="orbit" class="wide" src="desktop/turntable-glb/frame-000.png" alt="实际Blender桌面旋转截图"></a><p><a href="qa/glb-desktop-orbit-contact-sheet.jpg">最终GLB9帧总览</a> · <a href="qa/desktop-orbit-contact-sheet.jpg">原场景25帧总览</a> · <a href="qa/desktop-orbit-events.json">实际输入记录</a> · <a href="qa/glb-final-orbit-closure.json">最终GLB360°闭合检查</a> · <a href="qa/desktop-glb-orbit-events.json">GLB旋转输入记录</a></p><h2>GLB重导入：浅色与深色背景</h2><div class="grid">''')
for angle in ['front-right','rear-left']:
 for bg in ['light','dark']:
  path=f'qa/glb-{angle}-{bg}.png';parts.append(f'<figure><a href="{path}"><img loading="lazy" src="{path}" alt="GLB {angle} {bg}"></a><figcaption>GLB {angle} / {bg}</figcaption></figure>')
parts.append('''</div><h2>imagegen与资料</h2><p>完整独立六视、斜视、俯仰视、草图与细节参考共22项最终选择；本轮实际新生成23张，另保留有效历史参考和已退回的生成结果。AI文字和尺寸没有用于最终品牌或精确几何。</p><nav><a href="references/SELECTED.txt">最终参考清单</a><a href="references/REVIEW-FINAL.md">参考审查与排除项</a><a href="references/manifest.json">提示词与生成来源索引</a><a href="EVIDENCE.md">各面证据与缺口</a><a href="textures/delivery/manifest.json">GLB的17张独立贴图</a></nav><script>let timer=null;const f=document.getElementById('frame');function show(){let n=Number(f.value),src='desktop/turntable-glb/frame-'+String(n).padStart(3,'0')+'.png';document.getElementById('orbit').src=src;document.getElementById('orbitlink').href=src;document.getElementById('angle').textContent=n*45+'°';}f.oninput=show;document.getElementById('play').onclick=()=>{if(timer){clearInterval(timer);timer=null}else timer=setInterval(()=>{f.value=(Number(f.value)+1)%9;show()},450)};</script></html>''')
(P/'REVIEW.html').write_text(''.join(parts));print('REVIEW.html written')
